export 'obtener_alumnos.dart' show obtenerAlumnos;
export 'obtener_asignaturas.dart' show obtenerAsignaturas;
export 'obtener_departamentos.dart' show obtenerDepartamentos;
export 'asociar_departamento.dart' show asociarDepartamento;
export 'asociar_asignatura.dart' show asociarAsignatura;
export 'obtener_profesores.dart' show obtenerProfesores;
export 'obtener_administradores.dart' show obtenerAdministradores;
export 'modificar_usuario.dart' show modificarUsuario;
export 'login_usuario.dart' show loginUsuario;
